<?php

/**
 * @file
 * Contains eureka_migration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function eureka_migration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the eureka_migration module.
    case 'help.page.eureka_migration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migration from Eureka legacy site into Drupal.') . '</p>';
      return $output;

    default:
  }
}
