<?php

/**
 * @file
 * Contains utexas_flipcard_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function utexas_flipcard_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the utexas_flipcard_block module.
    case 'help.page.utexas_flipcard_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Define a placeable block that has flipcard functionality') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function utexas_flipcard_block_theme($existing, $type, $theme, $path) {
  return [
    'utexas_flipcard_block' => [
      'variables' => [
        'front_text' => NULL,
        'front_color' => NULL,
        'back_text' => NULL,
        'back_color' => NULL,
        'id' => NULL,
      ],
      'template' => 'utexas-flipcard-block',
    ],
  ];
}
