<?php

/**
 * @file
 * Contains eureka_footer_content.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;


function eureka_footer_content_theme() {
  $theme['footer_left'] = [
    'variables' => ['name' => NULL, 'year' => NULL],
    'template' => 'footer-left'
  ];
  $theme['footer_right'] = [
    'variables' => ['name' => NULL, 'year' => NULL],
    'template' => 'footer-right'
  ];
  $theme['footer_upper'] = [
    'variables' => ['name' => NULL, 'year' => NULL],
    'template' => 'footer-upper'
  ];

  return $theme;
}
