<?php

/**
 * @file
 * Contains eureka_profile_entity.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\search_api\Entity\Index;

/**
 * Implements hook_form_alter().
 */
function eureka_profile_entity_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, array('user_form', 'user_register_form'))) {
    foreach ($form as $field => $values) {
      if (!empty($values['#parents'])) {
        $form[$field]['#group'] = key($values['#parents']);
      }
    }
    $form['#attached']['library'][] = 'eureka_profile_entity/user_form';
    // Set name & mail to non-required to override HTML5 validation.
    $form['account']['name']['#weight'] = -10;
    $form['account']['name']['#required'] = FALSE;
    $form['account']['name']['#title'] .= ' *';
    $form['account']['mail']['#weight'] = -9;
    $form['account']['mail']['#required'] = FALSE;
    $form['account']['mail']['#title'] .= ' *';
    $form['account']['pass']['#weight'] = -8;
    $form['account']['#group'] = 'group_account';

    // Suppress display of path setting for user accounts.
    $form['path']['#access'] = FALSE;
    $form['#validate'][] = '_eureka_profile_entity_validate';
  }
}

/**
 * General purpose function for any validation on the user account form.
 */
function _eureka_profile_entity_validate(&$form, FormStateInterface $form_state) {
  $roles = array_values($form_state->getValue('roles'));
  if (in_array('faculty', $roles)) {
    $required_fields = [
      'field_display_name' => 'text',
      'field_first_name' => 'text',
      'field_last_name' => 'text',
      'field_job_title' => 'term',
    ];
  }
  foreach ($required_fields as $key => $type) {
    _eureka_profile_entity_check_required($key, $type, $form_state);
  }
}

/**
 * Custom form validation logic for required fields.
 *
 * @param string $key
 *    The field's name (without field_).
 * @param string $type
 *   The field type.
 * @param FormStateInterface $form_state
 *   The form_state.
 */
function _eureka_profile_entity_check_required($key, $type, FormStateInterface $form_state) {
  $name = str_replace('field_', '', $key);
  $field = $form_state->getValue($key);
  switch ($type) {

    case 'text':
      // Note: this will only require the *first* instance of the field.
      $content = $field[0]['value'];
      break;

    case 'term':
      // Note: this will only require the *first* instance of the field.
      $content = $field[0]['target_id'];
      break;
  }

  if ($content == '') {
    $form_state->setErrorByName($key, t('The %name field is required.', ['%name' => $name]));
  }
}

/**
 * Implements hook_page_attachments_alter().
 *
 * Print user display name as the page title.
 */
function eureka_profile_entity_page_attachments_alter(array &$page) {
  $user = \Drupal::routeMatch()->getParameter('user');
  if ($user) {
    $config = \Drupal::config('system.site');
    $name = $user->get('field_display_name')->getString();
    if ($name && $name != ' ') {
      $page['#attached']['html_head'][] = [
        [
          '#tag' => 'title',
          '#value' => $name . ' | ' . $config->get('name'),
        ],
        'title',
      ];
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * Queue all projects for reindexing when user is updated.
 */
function eureka_profile_entity_user_update(EntityInterface $entity) {
  $projects = $entity->field_projects->getValue();
  if ($projects) {
    foreach ($projects as $project) {
      // Load the project node.
      $node = Node::load($project['target_id']);
      // Set the changed value so it isn't updated by save.
      $node->changed->value = $node->changed->value;
      // Save the project to mark it for reindexing.
      $node->save();
    }
  }
}
