<?php

/**
 * @file
 * Contains eureka_profile_entity.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function eureka_profile_entity_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, array('user_form', 'user_register_form'))) {
    $form['#attached']['library'][] = 'eureka_profile_entity/user_form';
    // Set name & mail to non-required to override HTML5 validation.
    $form['account']['name']['#weight'] = -10;
    $form['account']['name']['#required'] = FALSE;
    $form['account']['name']['#title'] .= ' *';
    $form['account']['mail']['#weight'] = -9;
    $form['account']['mail']['#required'] = FALSE;
    $form['account']['mail']['#title'] .= ' *';
    $form['account']['pass']['#weight'] = -8;
    // Suppress display of path setting for user accounts.
    $form['path']['#access'] = FALSE;
    $form['#validate'][] = '_eureka_profile_entity_validate';
  }
}

/**
 * General purpose function for any validation on the user account form.
 */
function _eureka_profile_entity_validate(&$form, FormStateInterface $form_state) {
  $required_fields = [
    'field_display_name' => 'text',
    'field_first_name' => 'text',
    'field_last_name' => 'text',
    'field_job_title' => 'term',
  ];
  foreach ($required_fields as $key => $type) {
    _eureka_profile_entity_check_required($key, $type, $form_state);
  }
}

/**
 * Custom form validation logic for required fields.
 *
 * @param string $key
 *    The field's name (without field_).
 * @param string $type
 *   The field type.
 * @param FormStateInterface $form_state
 *   The form_state.
 */
function _eureka_profile_entity_check_required($key, $type, FormStateInterface $form_state) {
  $name = str_replace('field_', '', $key);
  $field = $form_state->getValue($key);
  switch ($type) {
    case 'text':
      // Note: this will only require the *first* instance of the field.
      $content = $field[0]['value'];
      break;

    case 'term':
      // Note: this will only require the *first* instance of the field.
      $content = $field[0]['target_id'];
      break;
  }

  if ($content == '') {
    $form_state->setErrorByName($key, t('The %name field is required.', ['%name' => $name]));
  }
}
