<?php

/**
 * @file
 * Module file for eureka_contacted_faculty.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function eureka_bookmark_dashboard_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'project_flag_block')) {
    $view->element['#attached']['library'][] = 'eureka_bookmark_dashboard/eureka-bookmark-dashboard';
  }
}
