<?php

/**
 * @file
 * Contains eureka_project_ct.module..
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Implements hook_form_alter().
 */
function eureka_project_ct_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if (in_array($form_id, ['node_project_edit_form', 'node_project_form'])) {

    // Suppress display of path setting for user accounts.
    $form['path']['#access'] = FALSE;

    $form['faculty_info'] = [
      '#type' => 'details',
      '#title' => 'Faculty',
      '#group' => 'advanced',
      '#open' => TRUE,
    ];
    $form['faculty_info']['field_project_lead'] = $form['field_project_lead'];
    unset($form['field_project_lead']);
    $form['faculty_info']['field_faculty_collaborators'] = $form['field_faculty_collaborators'];
    unset($form['field_faculty_collaborators']);

    $form['contact_info'] = [
      '#type' => 'details',
      '#title' => 'Contact Information *',
      '#group' => 'advanced',
      '#open' => TRUE,
    ];
    $fields = [
      'field_contact_name',
      'field_contact_email',
    ];

    foreach ($fields as $machine_name) {
      $form['contact_info'][$machine_name] = $form[$machine_name];
      unset($form[$machine_name]);
    }

    $form['#attached']['library'][] = 'eureka_project_ct/project_form';

    // Add Custom Submit Handler for adding Project to Project Lead.
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'eureka_project_ct_node_form_submit';
      }
    }

  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function eureka_project_ct_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  $changes = [
    'field_faculty_collaborators' => 'Add another faculty',
    'field_project_tags' => 'Add another tag',
    'field_tags' => 'Add another tag',
    'field_external_projects' => 'Add another project URL',
  ];

  $field = $context['items']->getFieldDefinition();

  $field_storage = $field->getFieldStorageDefinition();
  if ($field_storage->getCardinality() == FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED) {
    $name = $field->getName();
    if (in_array($name, array_keys($changes))) {
      $element['#custom_add_another_value'] = $changes[$name];
    }
  }
}

/**
 * Implements hook_preprocess_field_multiple_value_form().
 *
 * We look for a value that was placed there earlier by
 * custom_add_another_field_widget_form_alter() and change the add_more button
 * to use that.
 */
function eureka_project_ct_preprocess_field_multiple_value_form(&$variables) {
  foreach (Element::children($variables['element']) as $child) {
    $child_element = &$variables['element'][$child];
    if (isset($child_element['#custom_add_another_value']) || isset($child_element['#custom_remove'])) {
      if (isset($child_element['#custom_add_another_value']) && isset($variables['element']['add_more']['#value']) && $variables['element']['add_more']['#value'] != $child_element['#custom_add_another_value']) {
        $variables['element']['add_more']['#value'] = $child_element['#custom_add_another_value'];
      }
      if (isset($child_element['#custom_add_another_value']) && isset($variables['button']['#value']) && $variables['button']['#value'] != $child_element['#custom_add_another_value']) {
        $variables['button']['#value'] = $child_element['#custom_add_another_value'];
      }
      if (isset($child_element['#custom_remove']) && isset($child_element['remove_button']['#value'])) {
        $child_element['remove_button']['#value'] = $child_element['#custom_remove'];
      }
    }
  }
}

/**
 * Custom Submit Handler for Project nodes.
 *
 * Append Project to Project Lead's known projects. Remove from previous
 * Project Lead's profile if updating Project Lead.
 *
 * 3 situations exist:
 * 1. New project - result: Add project id to lead's profile.
 * 2. Current Project/Same Lead - result: Do Nothing.
 * 3. Current Project/New Lead - result: Remove project id from old lead's
 *    profile, then add add project id to new lead's profile.
 */
function eureka_project_ct_node_form_submit($form, FormStateInterface $form_state) {
  // Grab Project and User information from saved form.
  $project_id = $form_state->getValue('nid');
  $new_lead_id = $form_state->getValue('field_project_lead')[0]['target_id'];

  // Check if any other users are listed as Project Lead.
  $query = \Drupal::entityQuery('user')
    ->condition('roles', 'faculty')
    ->condition('field_projects', $project_id);
  $uids = $query->execute();

  // New Project if no query results.
  if (!$uids) {
    // Situation 1.
    add_project_user($new_lead_id, $project_id);
  }
  else {
    // Current Project.
    foreach ($uids as $existing_lead_id) {
      // Check if Project Lead has changed.
      if ($existing_lead_id != $new_lead_id) {
        // Situation 3.
        $situation = 'three';
      }
      else {
        // Situation 2.
        $situation = 'two';
      }

      switch ($situation) {
        case 'three':
          remove_project_user($existing_lead_id, $project_id);
          add_project_user($new_lead_id, $project_id);
          break;

        case 'two':
          break;
      }
    }
  }
}

/**
 * Add Project to User Profile.
 *
 * Given a Project ID and User ID, add Project to User's Project list.
 */
function add_project_user($uid, $proj_id) {
  $next_delta = db_select('user__field_projects', 'fp')
    ->fields('fp', ['delta'])
    ->condition('entity_id', $uid)
    ->orderBy('fp.delta', 'DESC')
    ->range(0, 1)
    ->execute()->fetchField() + 1;

  db_insert('user__field_projects')
    ->fields([
      'bundle' => 'user',
      'entity_id' => $uid,
      'revision_id' => $uid,
      'langcode' => 'en',
      'delta' => $next_delta,
      'field_projects_target_id' => $proj_id,
    ])
    ->execute();
}

/**
 * Remove Project from User Profile.
 *
 * Given a Project ID and User ID, remove Project from User's Project list.
 */
function remove_project_user($uid, $proj_id) {
  db_delete('user__field_projects')
    ->condition('entity_id', $uid)
    ->condition('field_projects_target_id', $proj_id)
    ->execute();
}
